### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [rdf-ext/rdf-data-model#1]
Hi,

Please tag releases as git tags.

That helps people redistributing the project (like me for Debian just now...) to track released code together with its underlying git commits.

**Comment by bergos** [comment]
Sorry,  `npm version` takes care of creating the tags, but I forgot to push it. Will try to keep the tags push discipline in the future!

**Comment by jonassmedegaard** [comment]
Quoting Thomas Bergwinkl (2018-01-06 22:03:15)
> Sorry,  `npm version` takes care of creating the tags, but I forgot to push it. Will try to keep the tags push discipline in the future!

Thanks. Also for the swift response :-)

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
